### ISSUE TITLE
Implementing aggregation endpoint(s) for /contributions

### ISSUE THREAD

**Issue by KowatschFab** [GIScience/ohsome-api#115]
This continues with the original idea about the /contributions endpoint defined in https://github.com/GIScience/ohsome-api/issues/23.

- [x] needs https://github.com/GIScience/ohsome-api/issues/117 to be solved

A `/contributions/count` endpoint would be useful e.g. for the last edit indicator in the OQT, where the number of edits (=contributions) is the required measure.

- [x] `/contributions/count` :arrow_right: #121 
- [x] `/contributions/count/groupBy/boundary` :arrow_right: #217
- [ ] `/contributions/count/groupBy/contributionType`
- `/contributions/count/groupBy/_additional_grouping_type(tbd)`

**Comment by FabiKo117** [comment]
Parts of the here mentioned features will be implemented with #121. Therefore, I'll remove the 1.4 milestone for now while still letting the issue open, as the other endpoints will most likely follow soon.

**Comment by Hagellach37** [comment]
We are moving towards ohsome API v2.0.
Hence, this topic will not be followed up on.

Feel free to raise it again if it is still relevant for the new API version.
